Fix `digits` not being optional
Fixes #77.

* * *

According to the
https://github.com/google/google-authenticator/wiki/Key-Uri-Format#digits,
`digits` parameter should be **optional**. It is not, e.g. after using
this URI:

```
otpauth://totp/Example:alice@google.com?secret=JBSWY3DPEHPK3PXP&issuer=Example
```

The application raises this error:

```
[2023-12-22 18:36:00,369] DEBUG:otp:352: 1 validation error for Uri
schema_ -> TOTPUriSchema -> parameters -> digits
  field required (type=value_error.missing)
Usage: otp add uri [OPTIONS] ALIAS
Try 'otp add uri -h' for help.

Error: invalid URI
```