Pin `pip`
To fix <https://github.com/pdm-project/pdm/issues/874>
resulting in:
```
[TypeError]: unpack_url() missing 1 required positional argument:
'verbosity'
```