Fix #51 (#52)
* Fix #51

* Fix `click` pre-commit issue

```
ImportError: cannot import name '_unicodefun' from 'click' (/pc/clone/OjKGFA1sRlaKkrrCMZD1Rg/py_env-python3.10/lib/python3.10/site-packages/click/__init__.py)
```

* Upgrade `pdm` in CI/CD

```
[TypeError]: unpack_url() missing 1 required positional argument: 'verbosity'
```

* Update the `pdm.lock`